spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081/
          predicates:
            - Path=/api/users/**
        - id: auth-service
          uri: http://localhost:8082/
          predicates:
            - Path=/api/auth/**
        - id: game-service
          uri: http://localhost:8083/
          predicates:
            - Path=/api/games/**
        - id: collection-service
          uri: http://localhost:8084/
          predicates:
            - Path=/api/collections/**
        - id: collection-diary-service
          uri: http://localhost:8084/
          predicates:
            - Path=/api/diary/**

#logging:
#  level:
#    org.springframework.cloud.gateway: TRACE
#    reactor.netty: TRACE

